spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

jwt:
  secret: my-super-secret-key-that-is-at-least-32-characters-long